Update client.go
valyala/fasthttp pull request #1558
Opened 2023-05-09 11:11 UTC by byte0o

fix client http SetReadDeadline/SetWriteDeadline Deadline is reused

2023-05-11 08:04 UTC, erikdubbelboer requested changes
Great find!

It seems like you have to run gofmt to format the code properly. You're using spaces now but Go code is always indented with tabs.

The comments also aren't needed.

And it seems like some tests are failing now because they don't expect these functions to be called. Can you look into that?

2023-05-14 10:06 UTC, byte0o commented on client.go
> +	// fix Deadline is reused
done

2023-05-14 10:06 UTC, byte0o commented on client.go
> +	// fix Deadline is reused
done

2023-05-14 10:17 UTC, byte0o commented on client.go
> +	// fix Deadline is reused
The test failed because the tested Conn did not implement the correct SetWriteDeadline/SetReadDeadline func,Already fixed

2023-05-14 10:55 UTC, merged

2023-05-14 10:55 UTC, erikdubbelboer commented
Thanks!

2023-06-09 19:46 UTC, ReneWerner87 commented
i have tested fiber with the master version and found this error

![image](https://github.com/valyala/fasthttp/assets/7063188/ca5c98c5-8b16-4c51-b3e5-aef705edbd1b)
![image](https://github.com/valyala/fasthttp/assets/7063188/4041f2c6-3d25-4000-acfb-e167446f2441)

![image](https://github.com/valyala/fasthttp/assets/7063188/28d7127d-20b0-476c-ac8b-051e7f23965b)

do i have to adjust anything else for us or is it a real error that has not been noticed ? 
@byte0o @erikdubbelboer 

https://github.com/gofiber/fiber/blob/9effdf829a79df49c24318bf753f8332d6e75375/client_test.go#L608-L642

2023-06-10 14:50 UTC, erikdubbelboer commented
@ReneWerner87 as you can see from the stacktrace the errors is in `(*readErrorConn).SetWriteDeadline` which doesn't exist in https://github.com/gofiber/fiber/blob/master/client_test.go#L584 so I'm not sure which code you are running? But the issue isn't in fasthttp.

2023-06-10 15:13 UTC, ReneWerner87 commented
Ok I see, so we need to add these 2 methods to our test connection as well

Thank you for the clarification
(have a nice weekend)