Allow redirect URI path to not be normalized.
valyala/fasthttp pull request #1638
Opened 2023-10-26 22:06 UTC by skidder

Fix #1637 

Propagates the `DisablePathNormalizing` setting on a request URI to the redirect URI. This fixes an issue where redirect URIs were being normalized regardless of the setting on the request URI. This could effectively break the redirect URI, depending on the expectations of the server.

Preserves the current default behavior, which is for `DisablePathNormalizing` to be `false`.

2023-10-26 22:45 UTC, kirillDanshin commented
I would consider this approach a breaking change though.
The issue is that users already got used to the existing meaning of this parameter, so I would rather this be done via a new option.
What do you think?
/cc @erikdubbelboer

2023-10-26 23:25 UTC, skidder commented
> I would consider this approach a breaking change though. The issue is that users already got used to the existing meaning of this parameter, so I would rather this be done via a new option. What do you think? /cc @erikdubbelboer

@kirillDanshin  Ah, good point. It sounds like you're proposing we signal to not normalize redirect locations using a new field on the request, is that right?

2023-10-29 08:04 UTC, erikdubbelboer requested changes

2023-10-29 08:04 UTC, erikdubbelboer commented on http.go
> +	// extra slashes are removed, special characters are encoded.
```suggestion
	// DisableRedirectPathNormalizing disables redirect path normalization when used with DoRedirects.
	//
	// By default redirect path values are normalized, i.e.
	// extra slashes are removed, special characters are encoded.
```
In Go, comments for fields or functions should start the the name of that field or function.

2023-10-30 18:08 UTC, merged