feat:support zstd compress and uncompressed
valyala/fasthttp pull request #1701
Opened 2024-01-31 14:07 UTC by Max-Cheng

2024-01-31 23:45 UTC, erikdubbelboer requested changes
Tests are failing.

2024-02-01 05:05 UTC, Max-Cheng commented
> Tests are failing.

Cause [compress](https://github.com/klauspost/compress) is declaring `go.mod' with `go 1.19'. In this case, I'll downgrade the version.

2024-02-02 05:07 UTC, erikdubbelboer commented
Still failing.

2024-02-02 06:23 UTC, Max-Cheng commented
> Still failing.

Ok. Looks like 1.18 `encoding/binary` does not implement `AppendByteOrder`.
[1.18](https://cs.opensource.google/go/go/+/release-branch.go1.18:src/encoding/binary/binary.go)
[1.19](https://cs.opensource.google/go/go/+/release-branch.go1.19:src/encoding/binary/binary.go;drc=986b04c0f12efa1c57293f147a9e734ec71f0363;l=46)

I will fix this in other ways.

2024-02-03 02:23 UTC, gaby commented
Compress minimum Go version is 1.19, downgrading is not a good idea since it will *not* have the corruption fixes made to `zstd` recently.

@erikdubbelboer Any timeline for fasthttp to bump the min go version?

2024-02-03 03:24 UTC, erikdubbelboer commented
I'm ok with you dropping 1.18 support in this pull. It's not officially maintained by the Go team either.

2024-02-03 04:18 UTC, gaby requested changes

2024-02-03 04:18 UTC, gaby commented on go.mod
> +	github.com/klauspost/compress v1.17.2
This should be v1.17.5

2024-02-06 00:27 UTC, gaby commented on go.mod
> +	github.com/klauspost/compress v1.17.2
v1.17.6 was released today

2024-02-06 07:04 UTC, Max-Cheng commented on go.mod
> +	github.com/klauspost/compress v1.17.2
Glad to see that, I'll update later.

2024-02-08 13:37 UTC, gaby commented on zstd.go
> +	return AppendZstdBytesLevel(dst, src, CompressZstdDefault)
Good catch!

2024-02-10 09:39 UTC, erikdubbelboer requested changes
There are still linting errors and it needs to be rebased on master now.

2024-02-11 03:31 UTC, Max-Cheng commented
Please Hold. I'll fix this error by rebase error

2024-02-12 12:50 UTC, Max-Cheng commented
@erikdubbelboer fixed

2024-02-13 05:44 UTC, gaby commented
@erikdubbelboer The timeouts in the tests are too agressive. The same error happens in a different PR

https://github.com/valyala/fasthttp/actions/runs/7881870997/job/21506194694?pr=1720

2024-02-20 14:11 UTC, alexandear commented on .github/workflows/test.yml
> +        go-version: [1.19.x, 1.20.x, 1.21.x]
I'm curious, do we need to change supported versions in this PR?

2024-02-20 14:13 UTC, gaby commented
@alexandear @erikdubbelboer @Max-Cheng Can someone rebase with master to see what's left on this PR?

2024-02-21 05:29 UTC, gaby commented
@erikdubbelboer If you add this to the lint workflow before the job, it will show you here on Github where the issues are:

```yaml
permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: Allow write access to checks to allow the action to annotate code in the PR.
  checks: write
```

Example: https://github.com/gofiber/fiber/blob/main/.github/workflows/linter.yml

2024-02-21 05:46 UTC, erikdubbelboer commented
@gaby thanks for the suggestion. I think everything is fixed now and this can be merged.

2024-02-21 06:21 UTC, merged