fix: close connection
valyala/fasthttp pull request #1755
Opened 2024-04-10 01:31 UTC by testwill

2024-04-10 21:18 UTC, erikdubbelboer requested changes

2024-04-10 21:18 UTC, erikdubbelboer commented on fasthttpproxy/proxy_env.go
> +			conn.Close()
```suggestion
			if connErr := conn.Close(); connErr != nil {
				return nil, fmt.Errorf("conn close err %v preceded by conn write err %w", connErr, err)
			}
```

2025-01-26 17:25 UTC, gaby approved these changes
👍 LGTM

2025-01-27 06:08 UTC, erikdubbelboer commented
@testwill can you resolve the merge conflict first?

2025-07-27 06:22 UTC, closed without merging