Fix possible race condition on request ctx done #1662
valyala/fasthttp pull request #1806
Opened 2024-07-16 12:03 UTC by byte0o

Fix possible race condition on request ctx done #1662

2024-07-17 16:40 UTC, erikdubbelboer commented
Almost all tests are failing.

2024-07-18 00:12 UTC, byte0o commented
> Almost all tests are failing.

@erikdubbelboer  
I tested it on this machine and the test failed due to timeout. The code I submitted will not have this problem because the previous pull request was also a test timeout.

2024-07-18 01:03 UTC, byte0o commented
> Almost all tests are failing.

@erikdubbelboer  This is caused by the test taking too long. I will check the reason.

2024-07-18 02:02 UTC, byte0o commented
> Almost all tests are failing.

@erikdubbelboer Handled, it is a deadlock caused by using lock

2024-07-21 13:16 UTC, erikdubbelboer requested changes

2024-07-21 13:16 UTC, erikdubbelboer commented on server.go
> +	case <-ctx.Done(): // fix  Use unified functions instead of reference variables to converge fetching into one place
```suggestion
	case <-ctx.Done():
```
No need to add this as a comment.

2024-07-22 00:05 UTC, byte0o commented on server.go
> +	case <-ctx.Done(): // fix  Use unified functions instead of reference variables to converge fetching into one place
Already processed

2024-07-23 19:15 UTC, merged

2024-07-23 19:16 UTC, erikdubbelboer commented
Thanks!