StreamRequestBody shouldn't read more data than actual need.
valyala/fasthttp pull request #1819
Opened 2024-08-05 21:47 UTC by newacorn

The StreamRequestBody feature on the server side should not read content that does not belong to the current request body.This is more logical and consistent with the result of not using the StreamRequestBody feature.
Fixes: [#1816](https://github.com/valyala/fasthttp/issues/1816). 
The reason for addressing this issue is that the Read method of requestStream assumes it should only read up to the Content-Length number of bytes.

2024-08-05 22:16 UTC, newacorn commented
https://github.com/valyala/fasthttp/blob/1fb34531652380677219b7c8c9c3d02da007a80b/http.go#L2286
Here, contentLength is guaranteed to be greater than or equal to 0 because the ContinueReadBodyStream function has already filtered out cases where contentLength is less than 0. It is assumed that a negative Content-Length value other than -1 should not be processed：
https://github.com/valyala/fasthttp/blob/1fb34531652380677219b7c8c9c3d02da007a80b/http.go#L1372

Below code will also handle cases where maxBodySize is less than contentLength.
https://github.com/valyala/fasthttp/blob/1fb34531652380677219b7c8c9c3d02da007a80b/http.go#L2295

2024-08-07 16:23 UTC, erikdubbelboer requested changes
Thanks, the fix looks good. But the new file needs to be formatted. And http.go needs some more newlines:
```
  http.go:2287: line is 147 characters (lll)
  		A fixed-length pre-read function should be used here; otherwise, it may read content beyond the request body into areas outside of the br buffer.
  http.go:2288: line is 160 characters (lll)
  	        This could affect the handling of the next request in the br buffer, if there is one. The original two branches can be handled with this single branch.
```

2024-08-10 09:38 UTC, erikdubbelboer requested changes

2024-08-10 09:38 UTC, erikdubbelboer commented on http.go
```suggestion
```
Sorry, our strict linter doesn't like this empty line here.

2024-08-10 09:38 UTC, erikdubbelboer commented on server_test.go
> +	//
```suggestion

```

2024-08-10 19:59 UTC, newacorn commented
@erikdubbelboer  May I ask what tools you use to lint the fasthttp codebase?

2024-08-11 13:15 UTC, erikdubbelboer commented
@newacorn you can see that here: https://github.com/valyala/fasthttp/blob/38a91cda6fa7e351834c1a7d97db9b89feec78c2/.github/workflows/lint.yml#L26-L28

2024-08-11 13:35 UTC, merged

2024-08-11 13:35 UTC, erikdubbelboer commented
Thanks!