fix gracefilly shutdown bug, issue #958
valyala/fasthttp pull request #960
Opened 2021-02-02 03:24 UTC by alpha-baby

### unit test

```bash
$ go test . -v -run=^TestShutdown$
=== RUN   TestShutdown
=== PAUSE TestShutdown
=== CONT  TestShutdown
--- PASS: TestShutdown (0.51s)
PASS
ok      github.com/valyala/fasthttp     0.530s
```

2021-02-06 08:56 UTC, erikdubbelboer commented
See: https://github.com/valyala/fasthttp/issues/958#issuecomment-774428181

2021-02-07 09:58 UTC, erikdubbelboer requested changes

2021-02-07 09:58 UTC, erikdubbelboer commented on server.go
> +	// refer isuee https://github.com/valyala/fasthttp/issues/958
```suggestion
	// CloseOnShutdown when true adds a `Connection: close` header when when the server is shutting down.
```

2021-02-07 11:56 UTC, alpha-baby commented
@erikdubbelboer can you fix this unit test, becase i'm not hava windwos PC.

2021-02-07 20:13 UTC, erikdubbelboer commented
The tests are a bit flaky, everything seems fine so I'm merging this. Thanks!

2021-02-07 20:13 UTC, merged